import streamlit as st
import joblib
from sentence_transformers import SentenceTransformer

# Page Config
st.set_page_config(
    page_title="Emotion Classifier",
    layout="centered"
)

# Header
st.title("📝 Emotion Classification App")

# Unified Information & Instructions
st.info(
    """
    💡 **About This App & How to Use It**
    
    This app predicts the emotion expressed in your text using a Logistic Regression model trained on embeddings 
    generated by a **Hugging Face model**: `sentence-transformers/all-MiniLM-L6-v2`. 
    
    Supported emotions are:  
    😢 sadness, 😄 joy, ❤️ love, 😡 anger, 😨 fear, 😲 surprise
    """
)

st.write(
    """
    **How to use:**
    1. Enter a sentence or phrase in the text area below.
    2. Click the **Predict** button.
    3. The predicted emotion will be displayed below.

    **Try different types of text to explore the model's predictions!**
    """
)

# Label Mapping
LABELS = ["sadness", "joy", "love", "anger", "fear", "surprise"]

# Emoji mapping for each emotion
EMOJI_MAP = {
    "sadness": "😢",
    "joy": "😄",
    "love": "❤️",
    "anger": "😡",
    "fear": "😨",
    "surprise": "😲"
}

# Load Model & Embeddings
@st.cache_resource
def load_model():
    embedder = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2")
    classifier = joblib.load("models/logistic_regression_emotion_model.pkl")
    return embedder, classifier

embedder, classifier = load_model()

# User Input
text_input = st.text_area(
    "Enter your text here:", 
    "",
    height=150
)

# Prediction Logic
if st.button("Predict"):
    if text_input.strip() == "":
        st.warning("⚠️ Please enter some text before predicting.")
    else:
        # Convert input to embeddings and predict
        embedding = embedder.encode([text_input])
        pred_idx = classifier.predict(embedding)[0]
        pred_label = LABELS[pred_idx]

        # Display prediction with corresponding emoji
        st.subheader("Prediction Result:")
        st.success(
            f"The model predicts the emotion as: {EMOJI_MAP.get(pred_label, '')} **{pred_label}**",
            icon="✅"
        )

# Footer / Additional Notes
st.markdown("---")
st.warning(
    "⚠️ **Note:** This model is trained on a specific dataset and may not be 100% accurate for all types of text. "
    "Feel free to experiment with different inputs to see how the model responds."
)
